# Dependencies
markdown:             redcarpet
highlighter:          rouge

permalink:            /:title
relative_permalinks:  false

title:                kmr
tagline:              Kelly Ripple
url:                  http://kellyripple.com
baseurl:              /

author:
  name:               'Kelly Ripple'
  url:                https://twitter.com/krippleffect
  email:              hello@kellyripple.com

github:
  repo:               https://github.com/kripple/kripple.github.io

environment:          development

exclude:              [node_modules,gulpfile.js,package.json,Gemfile,Rakefile]

